/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.prueba;

/**
 *
 * @author SEBASTIAN
 */
public class Seleccion extends javax.swing.JFrame {

    public Seleccion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Selección = new javax.swing.JLabel();
        botonTerminal = new javax.swing.JButton();
        botonSwingGUI = new javax.swing.JButton();
        Morfeo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elige pibe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Selección.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        Selección.setForeground(new java.awt.Color(255, 255, 255));
        Selección.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Selección.setText("SELECCIONE EL MODO DE VISUALIZACIÓN");
        Selección.setAlignmentX(0.5F);
        jPanel1.add(Selección, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 690, 90));

        botonTerminal.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        botonTerminal.setText("Terminal");
        botonTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminalActionPerformed(evt);
            }
        });
        jPanel1.add(botonTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 100, 40));

        botonSwingGUI.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        botonSwingGUI.setText("Swing GUI");
        botonSwingGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSwingGUIActionPerformed(evt);
            }
        });
        jPanel1.add(botonSwingGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 110, 40));

        Morfeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/imagenes/FondoSelección.png"))); // NOI18N
        jPanel1.add(Morfeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 710, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminalActionPerformed
        // TODO add your handling code here:
        InicioTerminal mainTerminal = new InicioTerminal();
        this.setVisible(false);
               
        mainTerminal.iniciarTerminal();
        System.exit(WIDTH);
    }//GEN-LAST:event_botonTerminalActionPerformed

    private void botonSwingGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSwingGUIActionPerformed
        // TODO add your handling code here:
        inicioSwingGUI obj1 = new inicioSwingGUI();
        obj1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSwingGUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Morfeo;
    private javax.swing.JLabel Selección;
    private javax.swing.JButton botonSwingGUI;
    private javax.swing.JButton botonTerminal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
