/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.clasesSwing;

import paquete.prueba.inicioSwingGUI;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author SEBASTIAN
 */
public class TresEnRayaSwing extends javax.swing.JFrame {

    /*
        ADAPTADO DEL TUTORIAL CREADO POR <<CODIGO LOBO>>
        https://youtu.be/FLIaI06wf0I
        ESTÉTICA Y FUNCIONALIDAD DE EMPATE AGREGADO
    */
    //si es true se puede escribir
    boolean estado=true;
    int cantidadMarcada = 1;
    String siguienteJuego="O";
    String turno="X";
    JLabel[] arrayCuadros=new JLabel[9];
    
    // Condiciones de victoria (lateral, vertical y diagonal)
    int condicionVictoria[][]=
    {
        {1,2,3},
        {4,5,6},
        {7,8,9},
        {1,4,7},
        {2,5,8},
        {3,6,9},
        {1,5,9},
        {3,5,7}
    };
    
    
    public TresEnRayaSwing() {
        initComponents();
        //primer [] es la quinta fila -1 y el segundo [] es la tercera posicion -1, porqw empieza a contar desde 0
        //System.out.println(condicionVictoria[4][2]);
        
        this.setLocationRelativeTo(null);
        arrayCuadros[0]=cuadro1;
        arrayCuadros[1]=cuadro2;
        arrayCuadros[2]=cuadro3;
        arrayCuadros[3]=cuadro4;
        arrayCuadros[4]=cuadro5;
        arrayCuadros[5]=cuadro6;
        arrayCuadros[6]=cuadro7;
        arrayCuadros[7]=cuadro8;
        arrayCuadros[8]=cuadro9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Título = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TablaDeJuego = new javax.swing.JPanel();
        cuadro1 = new javax.swing.JLabel();
        cuadro2 = new javax.swing.JLabel();
        cuadro3 = new javax.swing.JLabel();
        cuadro4 = new javax.swing.JLabel();
        cuadro5 = new javax.swing.JLabel();
        cuadro6 = new javax.swing.JLabel();
        cuadro7 = new javax.swing.JLabel();
        cuadro8 = new javax.swing.JLabel();
        cuadro9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lbturno = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        puntajeO = new javax.swing.JLabel();
        puntajeX = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tres en Raya");

        Título.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Título.setText("Tres en Raya");

        jButton1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jButton2.setText("Calculadora");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TablaDeJuego.setBackground(new java.awt.Color(255, 51, 0));

        cuadro1.setBackground(new java.awt.Color(255, 255, 255));
        cuadro1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro1.setOpaque(true);
        cuadro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro1MousePressed(evt);
            }
        });

        cuadro2.setBackground(new java.awt.Color(255, 255, 255));
        cuadro2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro2.setOpaque(true);
        cuadro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro2MousePressed(evt);
            }
        });

        cuadro3.setBackground(new java.awt.Color(255, 255, 255));
        cuadro3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro3.setOpaque(true);
        cuadro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro3MousePressed(evt);
            }
        });

        cuadro4.setBackground(new java.awt.Color(255, 255, 255));
        cuadro4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro4.setOpaque(true);
        cuadro4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro4MousePressed(evt);
            }
        });

        cuadro5.setBackground(new java.awt.Color(255, 255, 255));
        cuadro5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro5.setOpaque(true);
        cuadro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro5MousePressed(evt);
            }
        });

        cuadro6.setBackground(new java.awt.Color(255, 255, 255));
        cuadro6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro6.setOpaque(true);
        cuadro6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro6MousePressed(evt);
            }
        });

        cuadro7.setBackground(new java.awt.Color(255, 255, 255));
        cuadro7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro7.setOpaque(true);
        cuadro7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro7MousePressed(evt);
            }
        });

        cuadro8.setBackground(new java.awt.Color(255, 255, 255));
        cuadro8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro8.setOpaque(true);
        cuadro8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro8MousePressed(evt);
            }
        });

        cuadro9.setBackground(new java.awt.Color(255, 255, 255));
        cuadro9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cuadro9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro9.setOpaque(true);
        cuadro9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuadro9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout TablaDeJuegoLayout = new javax.swing.GroupLayout(TablaDeJuego);
        TablaDeJuego.setLayout(TablaDeJuegoLayout);
        TablaDeJuegoLayout.setHorizontalGroup(
            TablaDeJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaDeJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TablaDeJuegoLayout.createSequentialGroup()
                    .addComponent(cuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(cuadro3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablaDeJuegoLayout.createSequentialGroup()
                    .addComponent(cuadro4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(cuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(cuadro6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(TablaDeJuegoLayout.createSequentialGroup()
                .addComponent(cuadro7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuadro9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TablaDeJuegoLayout.setVerticalGroup(
            TablaDeJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaDeJuegoLayout.createSequentialGroup()
                .addGroup(TablaDeJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TablaDeJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadro4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TablaDeJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadro7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jButton3.setText("Reiniciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lbturno.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        lbturno.setText("Turno de X");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("X =");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setText("O=");

        puntajeO.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        puntajeO.setText("0");

        puntajeX.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        puntajeX.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbturno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(puntajeX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(puntajeO, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TablaDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(lbturno))
                .addGap(18, 18, 18)
                .addComponent(TablaDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajeO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajeX, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        jButton4.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jButton4.setText("Pokemon");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jButton6.setText("Editor de Texto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jButton5)
                        .addGap(102, 102, 102))))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(Título)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Título)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        inicioSwingGUI obj1 = new inicioSwingGUI();
        obj1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CalculadoraSwing obj2 = new CalculadoraSwing();
        obj2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cuadro1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro1MousePressed
        // TODO add your handling code here:
        presionar(1); cantidadMarcada++;
    }//GEN-LAST:event_cuadro1MousePressed

    private void cuadro2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro2MousePressed
        // TODO add your handling code here:
        presionar(2); cantidadMarcada++;
    }//GEN-LAST:event_cuadro2MousePressed

    private void cuadro3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro3MousePressed
        // TODO add your handling code here:
        presionar(3); cantidadMarcada++;
    }//GEN-LAST:event_cuadro3MousePressed

    private void cuadro4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro4MousePressed
        // TODO add your handling code here:
        presionar(4); cantidadMarcada++;
    }//GEN-LAST:event_cuadro4MousePressed

    private void cuadro5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro5MousePressed
        // TODO add your handling code here:
        presionar(5); cantidadMarcada++;
    }//GEN-LAST:event_cuadro5MousePressed

    private void cuadro6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro6MousePressed
        // TODO add your handling code here:
        presionar(6); cantidadMarcada++;
    }//GEN-LAST:event_cuadro6MousePressed

    private void cuadro7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro7MousePressed
        // TODO add your handling code here:
        presionar(7); cantidadMarcada++;
    }//GEN-LAST:event_cuadro7MousePressed

    private void cuadro8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro8MousePressed
        // TODO add your handling code here:
        presionar(8); cantidadMarcada++;
    }//GEN-LAST:event_cuadro8MousePressed

    private void cuadro9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadro9MousePressed
        // TODO add your handling code here:
        presionar(9); cantidadMarcada++;
    }//GEN-LAST:event_cuadro9MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cantidadMarcada = 1;
        for(int i=0; i< arrayCuadros.length; i++)
        {
            //todas las casillas vacias
            arrayCuadros[i].setText("");
            //todas las casillas en color blanco
            arrayCuadros[i].setBackground(Color.white);
        }
        
        turno=siguienteJuego;
        if (siguienteJuego.equalsIgnoreCase("O"))
        {
            siguienteJuego="X";
        }
        else
        {
            siguienteJuego="O";
        }
        
        lbturno.setText("Turno de " + turno);
        estado=true;
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BatallaPokemon2 obj4 = new BatallaPokemon2();
        obj4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        EditorTextoSwing objET = new EditorTextoSwing();
        objET.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    public void presionar(int casilla)
            //como empieza desde 0 siempre es -1
    {   if (arrayCuadros[casilla-1].getText().equals("") && estado)
        {
            arrayCuadros[casilla-1].setText(turno);
            cambiarTurno();
            comprobarGanador();
        }
    }
    public void cambiarTurno()
    {
        if(turno.equalsIgnoreCase("X"))
        {
            turno="O";
        }
        else
        {
            turno="X";
        }
        lbturno.setText("Turno de " + turno);
    }
    
    public void comprobarGanador()
    {
        for(int i=0; i< condicionVictoria.length; i++)
        {
            // Algoritmos para la detección de victoria
            if(arrayCuadros[condicionVictoria[i][0]-1].getText().equalsIgnoreCase("X") && 
                    arrayCuadros[condicionVictoria[i][1]-1].getText().equalsIgnoreCase("X") &&
                    arrayCuadros[condicionVictoria[i][2]-1].getText().equalsIgnoreCase("X"))
                
                
            {
                arrayCuadros[condicionVictoria[i][0]-1].setBackground(Color.GREEN);
                arrayCuadros[condicionVictoria[i][1]-1].setBackground(Color.GREEN);
                arrayCuadros[condicionVictoria[i][2]-1].setBackground(Color.GREEN);
                // El texto se convierte a entero se suma 1 punto y se castea a String.
                puntajeX.setText(Integer.toString(Integer.parseInt(puntajeX.getText())+1));
                
                lbturno.setText("Ha ganado X");
                estado=false;
                
            } else if (cantidadMarcada==9) {lbturno.setText("Se dio un empate");cantidadMarcada=1;}
            
            if(arrayCuadros[condicionVictoria[i][0]-1].getText().equalsIgnoreCase("O") && 
                    arrayCuadros[condicionVictoria[i][1]-1].getText().equalsIgnoreCase("O") &&
                    arrayCuadros[condicionVictoria[i][2]-1].getText().equalsIgnoreCase("O"))
                
                
            {
                arrayCuadros[condicionVictoria[i][0]-1].setBackground(Color.GREEN);
                arrayCuadros[condicionVictoria[i][1]-1].setBackground(Color.GREEN);
                arrayCuadros[condicionVictoria[i][2]-1].setBackground(Color.GREEN);
                
                puntajeO.setText(Integer.toString(Integer.parseInt(puntajeO.getText())+1));
                
                lbturno.setText("Ha ganado O");
                estado=false;

            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TresEnRayaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TresEnRayaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TresEnRayaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TresEnRayaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TresEnRayaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TablaDeJuego;
    private javax.swing.JLabel Título;
    private javax.swing.JLabel cuadro1;
    private javax.swing.JLabel cuadro2;
    private javax.swing.JLabel cuadro3;
    private javax.swing.JLabel cuadro4;
    private javax.swing.JLabel cuadro5;
    private javax.swing.JLabel cuadro6;
    private javax.swing.JLabel cuadro7;
    private javax.swing.JLabel cuadro8;
    private javax.swing.JLabel cuadro9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbturno;
    private javax.swing.JLabel puntajeO;
    private javax.swing.JLabel puntajeX;
    // End of variables declaration//GEN-END:variables
}
